# -*- coding: utf-8 -*-
"""22101169_Sabuj Majumder_CSE422_18_Assignment01_Fall2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgqDdMQedy7Wgw0HcN420NjPN6ZH2VkG
"""

import heapq

def createGH():
    r = open("/content/sample_data/input.txt", "r")
    l = r.read().splitlines()
    graph = {}
    h= {}

    for i in l:
        x = i.split()
        city = x[0]
        heu = int (x[1])
        h[city] = heu

        child = {}
        for j in range(2, len (x), 2):
            cty = x[j]
            d = int (x[j + 1])
            child[cty] = d

        graph[city] = child

    return graph, h


def a_star_search(graph, h, st, end):

    queue = []
    heapq.heappush(queue, (h[st], 0, st, [st]))

    short_cost = {st: 0}

    while (queue) :

        total_cost, c_cost, c_cty, path = heapq.heappop(queue)

        if c_cty == end:
            return path, c_cost

        for neighbor,cost in graph[c_cty].items():
            new_cost = c_cost + cost


            if neighbor not in short_cost :
                short_cost[neighbor] = new_cost
                total_cost = new_cost + h[neighbor]
                heapq.heappush(queue, (total_cost, new_cost, neighbor, path + [neighbor]))
            if new_cost < short_cost[neighbor]:
                short_cost[neighbor] = new_cost
                total_cost = new_cost + heuristics[neighbor]
                heapq.heappush(queue, (total_cost, new_cost, neighbor, path + [neighbor]))
    return 0


start = input("Start node: ")
end = input("Destination: ")



graph, heuristics = createGH()

path,distance= a_star_search(graph, heuristics, start, end )

if path == 0 :
    print("NO PATH FOUND")
else:
    st=""
    for i in path:
      st+="->"+i
    print("Path: "+ st[2::])
    print("Total distance:",distance, "km")