# -*- coding: utf-8 -*-
"""22101169_Sabuj Majumder_CSE422_18_Assignment03_Fall2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iM6GHYlmEI1h8oZviPyimnf_BU28eiQe

Part-1
"""

class Game:
    def __init__(self, start_player):
        self.start_player = start_player
        self.rounds = []
        self.total_rounds = 0

    def minimax(self, depth, player, alpha, beta):
        if depth == 0:
            if player == 0:
              return 1
            else:
              return 0

        if player == 0:
            max_value = float('-inf')
            for i in range(2):
                value = self.minimax(depth - 1, 1, alpha, beta)
                max_value = max(max_value, value)
                alpha = max(alpha, value)
                if beta <= alpha:
                    break
            return max_value
        else:
            min_value = float('inf')
            for i in range(2):
                value = self.minimax(depth - 1, 0, alpha, beta)
                min_value = min(min_value, value)
                beta = min(beta, value)
                if beta <= alpha:
                    break
            return min_value

    def play(self):
        current_player = self.start_player
        max_depth = 3

        while self.total_rounds < max_depth:
            result = self.minimax(max_depth, current_player, float('-inf'), float('inf'))
            if result == 1:
                result = "Scorpion"
            else:
                result = "Sub-Zero"
            self.rounds.append(result)
            self.total_rounds += 1
            current_player = 1 - current_player

        if self.rounds.count("Scorpion")> self.rounds.count("Sub-Zero"):
            game_winner = "Scorpion"
        else:
            game_winner = "Sub-Zero"
        return game_winner, self.total_rounds, self.rounds

def run(start_player):
    game = Game(start_player)
    game_winner, total_rounds, round_winners = game.play()

    print(f"Game Winner: {game_winner}")
    print(f"Total Rounds Played: {total_rounds}")
    for i in range(len(round_winners)):
        winner = round_winners[i]
        print(f"Winner of Round {i}: {winner}")


start_player = int(input("Enter the starting player (0/1) : "))
run(start_player)

"""Part-2"""

def minimax(depth, alpha, beta, player):
    if depth == 0:
        return [3, 6, 2, 3, 7, 1, 2, 0][depth]

    if player:
        best_value = float('-infinity')
        for i in range(2):
            value = minimax(depth - 1, alpha, beta, False)
            best_value = max(best_value, value)
            alpha = max(alpha, value)
            if beta <= alpha:
                break
        return best_value
    else:
        best_value = float('infinity')
        for i in range(2):
            value = minimax(depth - 1, alpha, beta, True)
            best_value = min(best_value, value)
            beta = min(beta, value)
            if beta <= alpha:
                break
        return best_value

def game(c):
    value_without_magic = minimax(2, float('-infinity'), float('infinity'), True)

    if value_without_magic <(max([3, 6, 2, 3, 7, 1, 2, 0])-c):
        return f"The new minimax value is {max([3, 6, 2, 3, 7, 1, 2, 0])-c}. Pacman goes right and uses dark magic"
    else:
        return f"The minimax value is {value_without_magic}. Pacman does not use dark magic"



print(game(int(input("Enter the move:"))))