# -*- coding: utf-8 -*-
"""22101169_Sabuj Majumder_CSE422_18_Assignment02_Fall2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLiaY5LiVHulm73epGJPhgztSnBVCVTx

Part-01
"""

import random

def fitness(chrom,course,slot):
    overlap=0
    consistancy=0
    list=[0]*course
    for i in range((slot)):
        start=i*(course)
        end=start+(course)
        individual=chrom[start:end]
        innerSlot=0
        for i in individual:
            if i == 1:
                innerSlot+=1
                list[individual.index(i)]+=1
        if innerSlot>1:
            overlap+=(innerSlot-1)

    for i in list:
        if i!=1:
            consistancy+=(abs(i-1))
    fitness=-(overlap+consistancy)
    return fitness

def population(course,slot):
  popu=[]
  for i in range(15):
    list=[]
    for i in range(course*slot):
       list.append(random.randint(0,1))
    popu.append(list)
  return popu


def select_parent(popu):
  child=random.sample(popu, 2)
  return child

def crossover(child):

  child1=child[0]
  child2=child[1]
  l=len(child1)-1
  idx= random.randint(1, l)
  child3 = child1[:idx] + child2[idx:]
  child4 = child2[:idx] + child1[idx:]
  return child3, child4

def mutation(child) :
    n=random.randint(0, len(child) - 1)
    child[n] = 1 - child[n]
    return child
def algo(child, course, slot):
    a, b = crossover(child)
    x = mutation(a)
    y = mutation(b)

    i=0
    while i<1000:
        n = fitness(x, course, slot)
        m = fitness(y, course, slot)

        if n == 0:
            print(x)
            print("Fitness:", n)
            return

        if m == 0:
            print(y)
            print("Fitness:", m)
            return


        a, b = crossover([x, y])
        x = mutation(a)
        y = mutation(b)
        i+=1


r = open("/content/sample_data/input.txt", "r")
l = r.read().splitlines()
course, slot= map(int, l[0].split())



total_popu=population(course,slot)
child=select_parent(total_popu)
algo(child,course,slot)

"""Part-02"""

def population(course,slot):
  popu=[]
  for i in range(15):
    list=[]
    for i in range(course*slot):
       list.append(random.randint(0,1))
    popu.append(list)

  child=random.sample(popu, 2)
  return child
def two_point_crossover(child):
    child1=child[0]
    child2=child[1]
    l = len(child1)
    point1 = random.randint(1, l - 2)
    point2 = random.randint(point1 + 1, l - 1)


    offspring1 = child1[:point1] + child2[point1:point2] + child1[point2:]
    offspring2 = child2[:point1] + child1[point1:point2] + child2[point2:]

    return offspring1, offspring2

r = open("/content/sample_data/input.txt", "r")
l = r.read().splitlines()
course, slot= map(int, l[0].split())
population(course,slot)